# Generated by Django 6.0.3 on 2026-07-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classe',
            name='classe_unique_par_niveau_code_section',
        ),
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='code',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='statuteleve',
            name='code',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('niveau', 'nom', 'section'), name='classe_unique_par_niveau_nom_section'),
        ),
    ]
