# Generated by Django 6.0.3 on 2026-07-14 23:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_remove_classe_classe_unique_par_niveau_code_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_active', models.BooleanField(default=False, verbose_name='Annee active')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
            ],
            options={
                'verbose_name': 'annee scolaire',
                'verbose_name_plural': 'annees scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name="Date d'inscription"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='eleves.anneescolaire', verbose_name='Annee scolaire'),
        ),
    ]
