# Generated by Django 6.0.3 on 2026-07-14 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_anneescolaire_alter_eleve_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numero de telephone invalide.', regex='^\\+?[\\d\\s().-]{9,25}$')], verbose_name='Telephone'),
        ),
    ]
