# Generated by Django 6.0.3 on 2026-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="nom de l'etablissement")),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='sigle')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
                ('devise', models.CharField(blank=True, max_length=255, verbose_name='devise')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='identite/logos/', verbose_name='logo')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
            ],
            options={
                'verbose_name': 'etablissement',
                'verbose_name_plural': 'etablissements',
            },
        ),
    ]
