# Generated by Django 6.0.3 on 2026-07-15 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0004_alter_eleve_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Type de frais')),
                ('code', models.SlugField(blank=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
            ],
            options={
                'verbose_name': 'type de frais',
                'verbose_name_plural': 'types de frais',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2eme trimestre'), (3, '3eme trimestre')], verbose_name='Trimestre')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total a payer')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolaires', to='eleves.anneescolaire', verbose_name='Annee scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_scolaires', to='eleves.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_scolaires', to='eleves.eleve', verbose_name='Eleve')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_scolaires', to='frais_scolaire.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'frais scolaire',
                'verbose_name_plural': 'frais scolaires',
                'ordering': ['eleve__nom', 'trimestre', 'type_frais'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant paye')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Especes'), ('mobile_money', 'Mobile Money'), ('banque', 'Virement bancaire'), ('cheque', 'Cheque'), ('carte', 'Carte bancaire')], max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Numero de recu')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annule'), ('en_attente', 'En attente')], default='valide', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Observations')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_scolaires_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve', verbose_name='Eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='frais_scolaire.fraisscolaire', verbose_name='Frais concerne')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_paiement', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='TarifFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2eme trimestre'), (3, '3eme trimestre')], verbose_name='Trimestre')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='eleves.anneescolaire', verbose_name='Annee scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='eleves.classe', verbose_name='Classe')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='eleves.niveau', verbose_name='Niveau')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='eleves.section', verbose_name='Section')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='frais_scolaire.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'tarif de frais',
                'verbose_name_plural': 'tarifs de frais',
                'ordering': ['annee_scolaire', 'trimestre', 'classe', 'type_frais'],
                'constraints': [models.UniqueConstraint(fields=('annee_scolaire', 'niveau', 'section', 'classe', 'trimestre', 'type_frais'), name='tarif_unique_par_annee_classe_trimestre_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='fraisscolaire',
            constraint=models.UniqueConstraint(fields=('eleve', 'annee_scolaire', 'trimestre', 'type_frais'), name='frais_unique_par_eleve_annee_trimestre_type'),
        ),
    ]
